title: Your first blog
author: Dingding User
email: HI@mydomain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog give you a new learning.

# social links
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
